title: "My Portfolio"
email: roshnyprince@gmail.com
description: "A portfolio to showcase my projects and skills."
baseurl: "" # Leave this empty
url: "https://roshnyprince90>.github.io"
theme: slate 
